/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.tests

import com.google.inject.Inject
import ic.ac.uk.itl.iTL.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(ITLInjectorProvider)
class ITLParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	
}
