/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.ui;

import ic.ac.uk.itl.ui.AbstractITLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ITLUiModule extends AbstractITLUiModule {
  public ITLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
