/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.ui.contentassist;

import ic.ac.uk.itl.ui.contentassist.AbstractITLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ITLProposalProvider extends AbstractITLProposalProvider {
}
