/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ic.ac.uk.itl.ITLRuntimeModule;
import ic.ac.uk.itl.ITLStandaloneSetup;
import ic.ac.uk.itl.ide.ITLIdeModule;
import ic.ac.uk.itl.web.ITLWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class ITLWebSetup extends ITLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ITLRuntimeModule _iTLRuntimeModule = new ITLRuntimeModule();
    ITLIdeModule _iTLIdeModule = new ITLIdeModule();
    ITLWebModule _iTLWebModule = new ITLWebModule();
    return Guice.createInjector(Modules2.mixin(_iTLRuntimeModule, _iTLIdeModule, _iTLWebModule));
  }
}
