/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.web;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import ic.ac.uk.itl.web.AbstractITLWebModule;
import ic.ac.uk.itl.web.ItlServiceDispatcher;
import org.eclipse.xtext.web.server.XtextServiceDispatcher;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class ITLWebModule extends AbstractITLWebModule {
  public Class<? extends XtextServiceDispatcher> bindXtextServiceDispatcher() {
    return ItlServiceDispatcher.class;
  }
  
  public void configureIResourceBaseProvider(final Binder binder) {
    AnnotatedBindingBuilder<IResourceBaseProvider> _bind = binder.<IResourceBaseProvider>bind(IResourceBaseProvider.class);
    ResourceBaseProviderImpl _resourceBaseProviderImpl = new ResourceBaseProviderImpl("./booster-files");
    _bind.toInstance(_resourceBaseProviderImpl);
  }
}
