/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.ui.tests;

import com.google.inject.Injector;
import ic.ac.uk.itl.ui.internal.ItlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ITLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ItlActivator.getInstance().getInjector("ic.ac.uk.itl.ITL");
	}

}
