/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ITLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractITLWebModule extends DefaultWebModule {

}
