/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractITLScopeProvider extends DelegatingScopeProvider {
}
