/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ic.ac.uk.itl.ITLRuntimeModule;
import ic.ac.uk.itl.ITLStandaloneSetup;
import ic.ac.uk.itl.ide.ITLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ITLIdeSetup extends ITLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ITLRuntimeModule _iTLRuntimeModule = new ITLRuntimeModule();
    ITLIdeModule _iTLIdeModule = new ITLIdeModule();
    return Guice.createInjector(Modules2.mixin(_iTLRuntimeModule, _iTLIdeModule));
  }
}
