/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.ide;

import ic.ac.uk.itl.ide.AbstractITLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ITLIdeModule extends AbstractITLIdeModule {
}
