/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl;

import ic.ac.uk.itl.ITLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ITLStandaloneSetup extends ITLStandaloneSetupGenerated {
  public static void doSetup() {
    new ITLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
