/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.serializer;

import com.google.inject.Inject;
import ic.ac.uk.itl.services.ITLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class ITLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ITLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_W3af_SemicolonKeyword_10_q;
	protected AbstractElementAlias match_ZAP_SemicolonKeyword_10_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ITLGrammarAccess) access;
		match_W3af_SemicolonKeyword_10_q = new TokenAlias(false, true, grammarAccess.getW3afAccess().getSemicolonKeyword_10());
		match_ZAP_SemicolonKeyword_10_q = new TokenAlias(false, true, grammarAccess.getZAPAccess().getSemicolonKeyword_10());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_W3af_SemicolonKeyword_10_q.equals(syntax))
				emit_W3af_SemicolonKeyword_10_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ZAP_SemicolonKeyword_10_q.equals(syntax))
				emit_ZAP_SemicolonKeyword_10_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     w3af_target=W3AF_TARGET (ambiguity) '}' (rule end)
	 */
	protected void emit_W3af_SemicolonKeyword_10_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     zap_api_key=ZAP_API_KEY (ambiguity) '}' (rule end)
	 */
	protected void emit_ZAP_SemicolonKeyword_10_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
