/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.iTL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ic.ac.uk.itl.iTL.ITLPackage
 * @generated
 */
public interface ITLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ITLFactory eINSTANCE = ic.ac.uk.itl.iTL.impl.ITLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>testing tool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>testing tool</em>'.
   * @generated
   */
  testing_tool createtesting_tool();

  /**
   * Returns a new object of class '<em>Spider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Spider</em>'.
   * @generated
   */
  Spider createSpider();

  /**
   * Returns a new object of class '<em>ZAP ADDRESS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ZAP ADDRESS</em>'.
   * @generated
   */
  ZAP_ADDRESS createZAP_ADDRESS();

  /**
   * Returns a new object of class '<em>ZAP MAX DEPTH</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ZAP MAX DEPTH</em>'.
   * @generated
   */
  ZAP_MAX_DEPTH createZAP_MAX_DEPTH();

  /**
   * Returns a new object of class '<em>ZAP API KEY</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ZAP API KEY</em>'.
   * @generated
   */
  ZAP_API_KEY createZAP_API_KEY();

  /**
   * Returns a new object of class '<em>ZAP TARGET</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ZAP TARGET</em>'.
   * @generated
   */
  ZAP_TARGET createZAP_TARGET();

  /**
   * Returns a new object of class '<em>W3af</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>W3af</em>'.
   * @generated
   */
  W3af createW3af();

  /**
   * Returns a new object of class '<em>W3AF REPORT ADDRESS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>W3AF REPORT ADDRESS</em>'.
   * @generated
   */
  W3AF_REPORT_ADDRESS createW3AF_REPORT_ADDRESS();

  /**
   * Returns a new object of class '<em>W3AF ADDRESS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>W3AF ADDRESS</em>'.
   * @generated
   */
  W3AF_ADDRESS createW3AF_ADDRESS();

  /**
   * Returns a new object of class '<em>W3AF TEST TYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>W3AF TEST TYPE</em>'.
   * @generated
   */
  W3AF_TEST_TYPE createW3AF_TEST_TYPE();

  /**
   * Returns a new object of class '<em>W3AF TARGET</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>W3AF TARGET</em>'.
   * @generated
   */
  W3AF_TARGET createW3AF_TARGET();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ITLPackage getITLPackage();

} //ITLFactory
