/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.iTL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ic.ac.uk.itl.iTL.ITLFactory
 * @model kind="package"
 * @generated
 */
public interface ITLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iTL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.ic/uk/itl/ITL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iTL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ITLPackage eINSTANCE = ic.ac.uk.itl.iTL.impl.ITLPackageImpl.init();

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.ModelImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Testing tools</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TESTING_TOOLS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.testing_toolImpl <em>testing tool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.testing_toolImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#gettesting_tool()
   * @generated
   */
  int TESTING_TOOL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_TOOL__NAME = 0;

  /**
   * The number of structural features of the '<em>testing tool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TESTING_TOOL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.ZAPImpl <em>ZAP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.ZAPImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP()
   * @generated
   */
  int ZAP = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP__NAME = TESTING_TOOL__NAME;

  /**
   * The feature id for the '<em><b>Zap target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP__ZAP_TARGET = TESTING_TOOL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Zap address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP__ZAP_ADDRESS = TESTING_TOOL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Zap max depth</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP__ZAP_MAX_DEPTH = TESTING_TOOL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Zap api key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP__ZAP_API_KEY = TESTING_TOOL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>ZAP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_FEATURE_COUNT = TESTING_TOOL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_ADDRESSImpl <em>ZAP ADDRESS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.ZAP_ADDRESSImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_ADDRESS()
   * @generated
   */
  int ZAP_ADDRESS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_ADDRESS__NAME = 0;

  /**
   * The number of structural features of the '<em>ZAP ADDRESS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_ADDRESS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_MAX_DEPTHImpl <em>ZAP MAX DEPTH</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.ZAP_MAX_DEPTHImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_MAX_DEPTH()
   * @generated
   */
  int ZAP_MAX_DEPTH = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_MAX_DEPTH__NAME = 0;

  /**
   * The number of structural features of the '<em>ZAP MAX DEPTH</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_MAX_DEPTH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_API_KEYImpl <em>ZAP API KEY</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.ZAP_API_KEYImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_API_KEY()
   * @generated
   */
  int ZAP_API_KEY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_API_KEY__NAME = 0;

  /**
   * The number of structural features of the '<em>ZAP API KEY</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_API_KEY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_TARGETImpl <em>ZAP TARGET</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.ZAP_TARGETImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_TARGET()
   * @generated
   */
  int ZAP_TARGET = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_TARGET__NAME = 0;

  /**
   * The number of structural features of the '<em>ZAP TARGET</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAP_TARGET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.W3afImpl <em>W3af</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.W3afImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3af()
   * @generated
   */
  int W3AF = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF__NAME = TESTING_TOOL__NAME;

  /**
   * The feature id for the '<em><b>W3af test type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF__W3AF_TEST_TYPE = TESTING_TOOL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>W3af address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF__W3AF_ADDRESS = TESTING_TOOL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>W3af report path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF__W3AF_REPORT_PATH = TESTING_TOOL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>W3af target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF__W3AF_TARGET = TESTING_TOOL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>W3af</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_FEATURE_COUNT = TESTING_TOOL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_REPORT_ADDRESSImpl <em>W3AF REPORT ADDRESS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.W3AF_REPORT_ADDRESSImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_REPORT_ADDRESS()
   * @generated
   */
  int W3AF_REPORT_ADDRESS = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_REPORT_ADDRESS__NAME = 0;

  /**
   * The number of structural features of the '<em>W3AF REPORT ADDRESS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_REPORT_ADDRESS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_ADDRESSImpl <em>W3AF ADDRESS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.W3AF_ADDRESSImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_ADDRESS()
   * @generated
   */
  int W3AF_ADDRESS = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_ADDRESS__NAME = 0;

  /**
   * The number of structural features of the '<em>W3AF ADDRESS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_ADDRESS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_TEST_TYPEImpl <em>W3AF TEST TYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.W3AF_TEST_TYPEImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_TEST_TYPE()
   * @generated
   */
  int W3AF_TEST_TYPE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_TEST_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>W3AF TEST TYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_TEST_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_TARGETImpl <em>W3AF TARGET</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.itl.iTL.impl.W3AF_TARGETImpl
   * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_TARGET()
   * @generated
   */
  int W3AF_TARGET = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_TARGET__NAME = 0;

  /**
   * The number of structural features of the '<em>W3AF TARGET</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int W3AF_TARGET_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see ic.ac.uk.itl.iTL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.itl.iTL.Model#getTesting_tools <em>Testing tools</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Testing tools</em>'.
   * @see ic.ac.uk.itl.iTL.Model#getTesting_tools()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Testing_tools();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.testing_tool <em>testing tool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>testing tool</em>'.
   * @see ic.ac.uk.itl.iTL.testing_tool
   * @generated
   */
  EClass gettesting_tool();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.testing_tool#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.testing_tool#getName()
   * @see #gettesting_tool()
   * @generated
   */
  EAttribute gettesting_tool_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.ZAP <em>ZAP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ZAP</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP
   * @generated
   */
  EClass getZAP();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.ZAP#getZap_target <em>Zap target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Zap target</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP#getZap_target()
   * @see #getZAP()
   * @generated
   */
  EReference getZAP_Zap_target();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.ZAP#getZap_address <em>Zap address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Zap address</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP#getZap_address()
   * @see #getZAP()
   * @generated
   */
  EReference getZAP_Zap_address();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.ZAP#getZap_max_depth <em>Zap max depth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Zap max depth</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP#getZap_max_depth()
   * @see #getZAP()
   * @generated
   */
  EReference getZAP_Zap_max_depth();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.ZAP#getZap_api_key <em>Zap api key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Zap api key</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP#getZap_api_key()
   * @see #getZAP()
   * @generated
   */
  EReference getZAP_Zap_api_key();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.ZAP_ADDRESS <em>ZAP ADDRESS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ZAP ADDRESS</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_ADDRESS
   * @generated
   */
  EClass getZAP_ADDRESS();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.ZAP_ADDRESS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_ADDRESS#getName()
   * @see #getZAP_ADDRESS()
   * @generated
   */
  EAttribute getZAP_ADDRESS_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.ZAP_MAX_DEPTH <em>ZAP MAX DEPTH</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ZAP MAX DEPTH</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_MAX_DEPTH
   * @generated
   */
  EClass getZAP_MAX_DEPTH();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.ZAP_MAX_DEPTH#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_MAX_DEPTH#getName()
   * @see #getZAP_MAX_DEPTH()
   * @generated
   */
  EAttribute getZAP_MAX_DEPTH_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.ZAP_API_KEY <em>ZAP API KEY</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ZAP API KEY</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_API_KEY
   * @generated
   */
  EClass getZAP_API_KEY();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.ZAP_API_KEY#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_API_KEY#getName()
   * @see #getZAP_API_KEY()
   * @generated
   */
  EAttribute getZAP_API_KEY_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.ZAP_TARGET <em>ZAP TARGET</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ZAP TARGET</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_TARGET
   * @generated
   */
  EClass getZAP_TARGET();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.ZAP_TARGET#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.ZAP_TARGET#getName()
   * @see #getZAP_TARGET()
   * @generated
   */
  EAttribute getZAP_TARGET_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.W3af <em>W3af</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>W3af</em>'.
   * @see ic.ac.uk.itl.iTL.W3af
   * @generated
   */
  EClass getW3af();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.W3af#getW3af_test_type <em>W3af test type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>W3af test type</em>'.
   * @see ic.ac.uk.itl.iTL.W3af#getW3af_test_type()
   * @see #getW3af()
   * @generated
   */
  EReference getW3af_W3af_test_type();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.W3af#getW3af_address <em>W3af address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>W3af address</em>'.
   * @see ic.ac.uk.itl.iTL.W3af#getW3af_address()
   * @see #getW3af()
   * @generated
   */
  EReference getW3af_W3af_address();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.W3af#getW3af_report_path <em>W3af report path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>W3af report path</em>'.
   * @see ic.ac.uk.itl.iTL.W3af#getW3af_report_path()
   * @see #getW3af()
   * @generated
   */
  EReference getW3af_W3af_report_path();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.itl.iTL.W3af#getW3af_target <em>W3af target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>W3af target</em>'.
   * @see ic.ac.uk.itl.iTL.W3af#getW3af_target()
   * @see #getW3af()
   * @generated
   */
  EReference getW3af_W3af_target();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.W3AF_REPORT_ADDRESS <em>W3AF REPORT ADDRESS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>W3AF REPORT ADDRESS</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_REPORT_ADDRESS
   * @generated
   */
  EClass getW3AF_REPORT_ADDRESS();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.W3AF_REPORT_ADDRESS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_REPORT_ADDRESS#getName()
   * @see #getW3AF_REPORT_ADDRESS()
   * @generated
   */
  EAttribute getW3AF_REPORT_ADDRESS_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.W3AF_ADDRESS <em>W3AF ADDRESS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>W3AF ADDRESS</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_ADDRESS
   * @generated
   */
  EClass getW3AF_ADDRESS();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.W3AF_ADDRESS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_ADDRESS#getName()
   * @see #getW3AF_ADDRESS()
   * @generated
   */
  EAttribute getW3AF_ADDRESS_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.W3AF_TEST_TYPE <em>W3AF TEST TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>W3AF TEST TYPE</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_TEST_TYPE
   * @generated
   */
  EClass getW3AF_TEST_TYPE();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.W3AF_TEST_TYPE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_TEST_TYPE#getName()
   * @see #getW3AF_TEST_TYPE()
   * @generated
   */
  EAttribute getW3AF_TEST_TYPE_Name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.itl.iTL.W3AF_TARGET <em>W3AF TARGET</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>W3AF TARGET</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_TARGET
   * @generated
   */
  EClass getW3AF_TARGET();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.itl.iTL.W3AF_TARGET#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.itl.iTL.W3AF_TARGET#getName()
   * @see #getW3AF_TARGET()
   * @generated
   */
  EAttribute getW3AF_TARGET_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ITLFactory getITLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.ModelImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Testing tools</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TESTING_TOOLS = eINSTANCE.getModel_Testing_tools();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.testing_toolImpl <em>testing tool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.testing_toolImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#gettesting_tool()
     * @generated
     */
    EClass TESTING_TOOL = eINSTANCE.gettesting_tool();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TESTING_TOOL__NAME = eINSTANCE.gettesting_tool_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.ZAPImpl <em>ZAP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.ZAPImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP()
     * @generated
     */
    EClass ZAP = eINSTANCE.getZAP();

    /**
     * The meta object literal for the '<em><b>Zap target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZAP__ZAP_TARGET = eINSTANCE.getZAP_Zap_target();

    /**
     * The meta object literal for the '<em><b>Zap address</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZAP__ZAP_ADDRESS = eINSTANCE.getZAP_Zap_address();

    /**
     * The meta object literal for the '<em><b>Zap max depth</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZAP__ZAP_MAX_DEPTH = eINSTANCE.getZAP_Zap_max_depth();

    /**
     * The meta object literal for the '<em><b>Zap api key</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZAP__ZAP_API_KEY = eINSTANCE.getZAP_Zap_api_key();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_ADDRESSImpl <em>ZAP ADDRESS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.ZAP_ADDRESSImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_ADDRESS()
     * @generated
     */
    EClass ZAP_ADDRESS = eINSTANCE.getZAP_ADDRESS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZAP_ADDRESS__NAME = eINSTANCE.getZAP_ADDRESS_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_MAX_DEPTHImpl <em>ZAP MAX DEPTH</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.ZAP_MAX_DEPTHImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_MAX_DEPTH()
     * @generated
     */
    EClass ZAP_MAX_DEPTH = eINSTANCE.getZAP_MAX_DEPTH();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZAP_MAX_DEPTH__NAME = eINSTANCE.getZAP_MAX_DEPTH_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_API_KEYImpl <em>ZAP API KEY</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.ZAP_API_KEYImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_API_KEY()
     * @generated
     */
    EClass ZAP_API_KEY = eINSTANCE.getZAP_API_KEY();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZAP_API_KEY__NAME = eINSTANCE.getZAP_API_KEY_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.ZAP_TARGETImpl <em>ZAP TARGET</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.ZAP_TARGETImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getZAP_TARGET()
     * @generated
     */
    EClass ZAP_TARGET = eINSTANCE.getZAP_TARGET();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZAP_TARGET__NAME = eINSTANCE.getZAP_TARGET_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.W3afImpl <em>W3af</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.W3afImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3af()
     * @generated
     */
    EClass W3AF = eINSTANCE.getW3af();

    /**
     * The meta object literal for the '<em><b>W3af test type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference W3AF__W3AF_TEST_TYPE = eINSTANCE.getW3af_W3af_test_type();

    /**
     * The meta object literal for the '<em><b>W3af address</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference W3AF__W3AF_ADDRESS = eINSTANCE.getW3af_W3af_address();

    /**
     * The meta object literal for the '<em><b>W3af report path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference W3AF__W3AF_REPORT_PATH = eINSTANCE.getW3af_W3af_report_path();

    /**
     * The meta object literal for the '<em><b>W3af target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference W3AF__W3AF_TARGET = eINSTANCE.getW3af_W3af_target();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_REPORT_ADDRESSImpl <em>W3AF REPORT ADDRESS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.W3AF_REPORT_ADDRESSImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_REPORT_ADDRESS()
     * @generated
     */
    EClass W3AF_REPORT_ADDRESS = eINSTANCE.getW3AF_REPORT_ADDRESS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute W3AF_REPORT_ADDRESS__NAME = eINSTANCE.getW3AF_REPORT_ADDRESS_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_ADDRESSImpl <em>W3AF ADDRESS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.W3AF_ADDRESSImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_ADDRESS()
     * @generated
     */
    EClass W3AF_ADDRESS = eINSTANCE.getW3AF_ADDRESS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute W3AF_ADDRESS__NAME = eINSTANCE.getW3AF_ADDRESS_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_TEST_TYPEImpl <em>W3AF TEST TYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.W3AF_TEST_TYPEImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_TEST_TYPE()
     * @generated
     */
    EClass W3AF_TEST_TYPE = eINSTANCE.getW3AF_TEST_TYPE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute W3AF_TEST_TYPE__NAME = eINSTANCE.getW3AF_TEST_TYPE_Name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.itl.iTL.impl.W3AF_TARGETImpl <em>W3AF TARGET</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.itl.iTL.impl.W3AF_TARGETImpl
     * @see ic.ac.uk.itl.iTL.impl.ITLPackageImpl#getW3AF_TARGET()
     * @generated
     */
    EClass W3AF_TARGET = eINSTANCE.getW3AF_TARGET();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute W3AF_TARGET__NAME = eINSTANCE.getW3AF_TARGET_Name();

  }

} //ITLPackage
