/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.iTL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.itl.iTL.Model#getTesting_tools <em>Testing tools</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.itl.iTL.ITLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Testing tools</b></em>' containment reference list.
   * The list contents are of type {@link ic.ac.uk.itl.iTL.testing_tool}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Testing tools</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Testing tools</em>' containment reference list.
   * @see ic.ac.uk.itl.iTL.ITLPackage#getModel_Testing_tools()
   * @model containment="true"
   * @generated
   */
  EList<testing_tool> getTesting_tools();

} // Model
