/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.iTL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>testing tool</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.itl.iTL.testing_tool#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.itl.iTL.ITLPackage#gettesting_tool()
 * @model
 * @generated
 */
public interface testing_tool extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ic.ac.uk.itl.iTL.ITLPackage#gettesting_tool_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ic.ac.uk.itl.iTL.testing_tool#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // testing_tool
