/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.iTL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ZAP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.itl.iTL.ZAP#getZap_target <em>Zap target</em>}</li>
 *   <li>{@link ic.ac.uk.itl.iTL.ZAP#getZap_address <em>Zap address</em>}</li>
 *   <li>{@link ic.ac.uk.itl.iTL.ZAP#getZap_max_depth <em>Zap max depth</em>}</li>
 *   <li>{@link ic.ac.uk.itl.iTL.ZAP#getZap_api_key <em>Zap api key</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP()
 * @model
 * @generated
 */
public interface ZAP extends testing_tool
{
  /**
   * Returns the value of the '<em><b>Zap target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Zap target</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zap target</em>' containment reference.
   * @see #setZap_target(ZAP_TARGET)
   * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP_Zap_target()
   * @model containment="true"
   * @generated
   */
  ZAP_TARGET getZap_target();

  /**
   * Sets the value of the '{@link ic.ac.uk.itl.iTL.ZAP#getZap_target <em>Zap target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zap target</em>' containment reference.
   * @see #getZap_target()
   * @generated
   */
  void setZap_target(ZAP_TARGET value);

  /**
   * Returns the value of the '<em><b>Zap address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Zap address</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zap address</em>' containment reference.
   * @see #setZap_address(ZAP_ADDRESS)
   * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP_Zap_address()
   * @model containment="true"
   * @generated
   */
  ZAP_ADDRESS getZap_address();

  /**
   * Sets the value of the '{@link ic.ac.uk.itl.iTL.ZAP#getZap_address <em>Zap address</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zap address</em>' containment reference.
   * @see #getZap_address()
   * @generated
   */
  void setZap_address(ZAP_ADDRESS value);

  /**
   * Returns the value of the '<em><b>Zap max depth</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Zap max depth</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zap max depth</em>' containment reference.
   * @see #setZap_max_depth(ZAP_MAX_DEPTH)
   * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP_Zap_max_depth()
   * @model containment="true"
   * @generated
   */
  ZAP_MAX_DEPTH getZap_max_depth();

  /**
   * Sets the value of the '{@link ic.ac.uk.itl.iTL.ZAP#getZap_max_depth <em>Zap max depth</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zap max depth</em>' containment reference.
   * @see #getZap_max_depth()
   * @generated
   */
  void setZap_max_depth(ZAP_MAX_DEPTH value);

  /**
   * Returns the value of the '<em><b>Zap api key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Zap api key</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zap api key</em>' containment reference.
   * @see #setZap_api_key(ZAP_API_KEY)
   * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP_Zap_api_key()
   * @model containment="true"
   * @generated
   */
  ZAP_API_KEY getZap_api_key();

  /**
   * Sets the value of the '{@link ic.ac.uk.itl.iTL.ZAP#getZap_api_key <em>Zap api key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zap api key</em>' containment reference.
   * @see #getZap_api_key()
   * @generated
   */
  void setZap_api_key(ZAP_API_KEY value);

} // ZAP
