/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.iTL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ZAP MAX DEPTH</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.itl.iTL.ZAP_MAX_DEPTH#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP_MAX_DEPTH()
 * @model
 * @generated
 */
public interface ZAP_MAX_DEPTH extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(int)
   * @see ic.ac.uk.itl.iTL.ITLPackage#getZAP_MAX_DEPTH_Name()
   * @model
   * @generated
   */
  int getName();

  /**
   * Sets the value of the '{@link ic.ac.uk.itl.iTL.ZAP_MAX_DEPTH#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(int value);

} // ZAP_MAX_DEPTH
