/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ITLStandaloneSetup extends ITLStandaloneSetupGenerated {

	def static void doSetup() {
		new ITLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
