/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ITLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ic/ac/uk/itl/parser/antlr/internal/InternalITL.tokens");
	}
}
