/*
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.parser.antlr;

import com.google.inject.Inject;
import ic.ac.uk.itl.parser.antlr.internal.InternalITLParser;
import ic.ac.uk.itl.services.ITLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ITLParser extends AbstractAntlrParser {

	@Inject
	private ITLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalITLParser createParser(XtextTokenStream stream) {
		return new InternalITLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ITLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ITLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
