/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.scoping;

import ic.ac.uk.itl.scoping.AbstractITLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ITLScopeProvider extends AbstractITLScopeProvider {
}
