/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.itl.validation;

import ic.ac.uk.itl.validation.AbstractITLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ITLValidator extends AbstractITLValidator {
}
